package com.sbga.sdgbapp.Net.VO.Mai2

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class UserDetail(
    @SerialName("accessCode") val accessCode: String,
    @SerialName("userName") val userName: String,
    @SerialName("isNetMember") val isNetMember: Int,
    @SerialName("iconId") val iconId: Int,
    @SerialName("plateId") val plateId: Int,
    @SerialName("titleId") val titleId: Int,
    @SerialName("partnerId") val partnerId: Int,
    @SerialName("frameId") val frameId: Int,
    @SerialName("selectMapId") val selectMapId: Int,
    @SerialName("totalAwake") val totalAwake: Int,
    @SerialName("gradeRating") val gradeRating: Int,
    @SerialName("musicRating") val musicRating: Int,
    @SerialName("playerRating") val playerRating: Int,
    @SerialName("highestRating") val highestRating: Int,
    @SerialName("gradeRank") val gradeRank: Int,
    @SerialName("classRank") val classRank: Int,
    @SerialName("courseRank") val courseRank: Int,
    @SerialName("charaSlot") val charaSlot: IntArray,
    @SerialName("charaLockSlot") val charaLockSlot: IntArray,
    @SerialName("contentBit") val contentBit: ULong,
    @SerialName("playCount") val playCount: Int,
    @SerialName("eventWatchedDate") val eventWatchedDate: String,
    @SerialName("lastGameId") val lastGameId: String,
    @SerialName("lastRomVersion") val lastRomVersion: String,
    @SerialName("lastDataVersion") val lastDataVersion: String,
    @SerialName("lastLoginDate") val lastLoginDate: String,
    @SerialName("lastPlayDate") val lastPlayDate: String,
    @SerialName("lastPlayCredit") val lastPlayCredit: Int,
    @SerialName("lastPlayMode") val lastPlayMode: Int,
    @SerialName("lastPlaceId") val lastPlaceId: Int,
    @SerialName("lastPlaceName") val lastPlaceName: String,
    @SerialName("lastAllNetId") val lastAllNetId: Int,
    @SerialName("lastRegionId") val lastRegionId: Int,
    @SerialName("lastRegionName") val lastRegionName: String,
    @SerialName("lastClientId") val lastClientId: String,
    @SerialName("lastCountryCode") val lastCountryCode: String,
    @SerialName("lastSelectEMoney") val lastSelectEMoney: Int,
    @SerialName("lastSelectTicket") val lastSelectTicket: Int,
    @SerialName("lastSelectCourse") val lastSelectCourse: Int,
    @SerialName("lastCountCourse") val lastCountCourse: Int,
    @SerialName("firstGameId") val firstGameId: String,
    @SerialName("firstRomVersion") val firstRomVersion: String,
    @SerialName("firstDataVersion") val firstDataVersion: String,
    @SerialName("firstPlayDate") val firstPlayDate: String,
    @SerialName("compatibleCmVersion") val compatibleCmVersion: String,
    @SerialName("dailyBonusDate") val dailyBonusDate: String,
    @SerialName("dailyCourseBonusDate") val dailyCourseBonusDate: String,
    @SerialName("lastPairLoginDate") val lastPairLoginDate: String,
    @SerialName("lastTrialPlayDate") val lastTrialPlayDate: String,
    @SerialName("playVsCount") val playVsCount: Int,
    @SerialName("playSyncCount") val playSyncCount: Int,
    @SerialName("winCount") val winCount: Int,
    @SerialName("helpCount") val helpCount: Int,
    @SerialName("comboCount") val comboCount: Int,
    @SerialName("totalDeluxscore") val totalDeluxscore: Long,
    @SerialName("totalBasicDeluxscore") val totalBasicDeluxscore: Long,
    @SerialName("totalAdvancedDeluxscore") val totalAdvancedDeluxscore: Long,
    @SerialName("totalExpertDeluxscore") val totalExpertDeluxscore: Long,
    @SerialName("totalMasterDeluxscore") val totalMasterDeluxscore: Long,
    @SerialName("totalReMasterDeluxscore") val totalReMasterDeluxscore: Long,
    @SerialName("totalSync") val totalSync: Int,
    @SerialName("totalBasicSync") val totalBasicSync: Int,
    @SerialName("totalAdvancedSync") val totalAdvancedSync: Int,
    @SerialName("totalExpertSync") val totalExpertSync: Int,
    @SerialName("totalMasterSync") val totalMasterSync: Int,
    @SerialName("totalReMasterSync") val totalReMasterSync: Int,
    @SerialName("totalAchievement") val totalAchievement: Long,
    @SerialName("totalBasicAchievement") val totalBasicAchievement: Long,
    @SerialName("totalAdvancedAchievement") val totalAdvancedAchievement: Long,
    @SerialName("totalExpertAchievement") val totalExpertAchievement: Long,
    @SerialName("totalMasterAchievement") val totalMasterAchievement: Long,
    @SerialName("totalReMasterAchievement") val totalReMasterAchievement: Long,
    @SerialName("playerOldRating") val playerOldRating: Long,
    @SerialName("playerNewRating") val playerNewRating: Long,
    @SerialName("banState") val banState: Int,
    @SerialName("dateTime") val dateTime: Long
)
